---
- name: deploy gameoflife
  hosts: all
  become: yes
  tasks:
    - name: install java-sdk
      apt:
        name: openjdk-8-jdk
        update_cache: yes
        state: present
    - name: install tomcat
      apt:
        name: tomcat8
        state: present
    - name: download jar file into webapps folder
      get_url:
        url: https://referenceapplicationskhaja.s3.us-west-2.amazonaws.com/gameoflife.war
        dest: /var/lib/tomcat8/webapps/gameoflife.war        


